### ISSUE TITLE
gitmoji -c don't run pre-commit hooks

### ISSUE THREAD

**Issue by flassagne** [carloscuesta/gitmoji-cli#345] opened 2020-04-03 09:04 UTC
Hello @carloscuesta!

If a use gitmoji-cli with `-c` option my pre-commit hooks are not used. 

Issue:

* install a pre-commit
* do some updates
* commit them with `gitmoji -c`  

**OS**: debian 10
**gitmoji-cli -v**: 3.2.3

**Node version**: v10.15.3

**Comment by carloscuesta** [comment] 2020-04-03 16:13
Could you provide a reproduction case?

Thanks

**Comment by flassagne** [comment] 2020-04-05 09:08
Hi @carloscuesta ,

I already did but I send you a complete example:

# First install a pre-commit hook in your repository

```bash
# Move in your repository
$ cat << EOF > .git/hooks/pre-commit
#!/bin/bash

echo "Run my pre-commit hook"
EOF

# Give executable rigth
$ sudo chmod +x .git/hooks/pre-commit
```

# Do some updates

 ```bash
$ touch a.yml
$ touch b.yml
```
# Commit then

## If I use `git commit` you see the hook execution

```bash
$ git add a.yml
$ git commit -m "commit with git commit command"
Run my pre-commit hook # <===
[master 82a13ec] a
 1 file changed, 1 insertion(+)
```
## If I use `gitmoji -c` you don't see the hook execution

```bash
$ git add b.yml
$ gitmoji -c
? Choose a gitmoji: ✨  - Introducing new features.
? Enter the commit title [27/48]: commit with gitmoji command
? Enter the commit message: 
[master d8e009a] ✨ commit with gitmoji command
 1 file changed, 1 insertion(+)
```

**Comment by carloscuesta** [comment] 2020-04-05 09:10
Sorry I mean the repository youre having trouble with. Because I use gitmoji -c with precommit hooks and had no problems

**Comment by flassagne** [comment] 2020-04-05 10:38
I think it's more a logging issue. When I use `gitmoji -c` my hook had run but I didn't see any logs.
It's maybe due to `execa` lib

**Comment by carloscuesta** [comment] 2020-04-06 07:32
Then, you don't have troubles when runnings hooks, but the logging that they provide you

**Comment by carloscuesta** [comment] 2020-04-06 07:33
I don't see problems with logging too, I'm going to close this if you can't provide a reproduction repository since I can't fix this

Thanks!

**Closed by carloscuesta** 2020-04-06 07:33 UTC

**Comment by muarachmann** [comment] 2020-09-05 11:16
Hi, I am having similar issue running with a pre-commit using the version `3.2.9`

 Here is what I get

```
A commit message is already set, cancelling gitmoji

error: cannot run gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
    at makeError (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/gitmoji-cli/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async withClient (/usr/local/lib/node_modules/gitmoji-cli/lib/commands/commit/withClient/index.js:33:9) {
  shortMessage: 'Command failed with exit code 128: git commit -S -m :zap: Improved code -m Modified readme, added commit instructions and also fixed language switcher on server side, fixed broken github action',
  command: 'git commit -S -m :zap: Improved code -m Modified readme, added commit instructions and also fixed language switcher on server side, fixed broken github action',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '\n' +
    'Validating PHPCS:\n' +
    '\n' +
    '. 1 / 1 (100%)\n' +
    '\n' +
    '\n' +
    'Time: 94ms; Memory: 8MB\n' +
    '\n' +
    '\t\x1B[32mPHPCS Passed: app/Exceptions/Handler.php\x1B[0m\n' +
    '. 1 / 1 (100%)\n' +
    '\n' +
    '\n' +
    'Time: 52ms; Memory: 8MB\n' +
    '\n' +
    '\t\x1B[32mPHPCS Passed: app/Http/Controllers/LocaleController.php\x1B[0m\n' +
    '\n' +
    'PHPCS validation completed!\n' +
    '\n' +
    '\x1B[42mCOMMIT SUCCEEDED\x1B[0m\n' +
    '\n' +
    'A commit message is already set, cancelling gitmoji\n' +
    '\n' +
    'error: cannot run gpg: No such file or directory\n' +
    'error: gpg failed to sign the data\n' +
    'fatal: failed to write commit object',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Baically I am just verifying the my code with code sniffer in my pre-commit. Any help would be appreciated.
