### ISSUE TITLE
with pre-commit 

### ISSUE THREAD

**Issue by linpan** [carloscuesta/gitmoji-cli#1031] opened 2023-03-14 05:32 UTC
### Describe the bug

pre-commit 

### Reproduction

pre-commit install 

### System Info

```Shell
will eror
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment] 2023-03-14 07:48
Hey!

I’ll close the issue since there’s not enough information to understand what’s going on and reproduce it

Thanks

**Closed by carloscuesta** 2023-03-14 07:48 UTC

**Comment by linpan** [comment] 2023-03-15 03:20
use .pre-commit-config.yaml
