### ISSUE TITLE
git hook should ignore fixup commits

### ISSUE THREAD

**Issue by zeenix** [carloscuesta/gitmoji-cli#1097] opened 2023-05-19 20:32 UTC
### Describe the bug

The commit message of a fixup commit (crated through `--fixup` option of `git commit`) is transient and has a very specific format that git picks up on during the rebase that follows.

It's not very bad though as I just hit CTRL+C at the gitmoji prompt and commit message is then how it should be. It would be better of course if I didn't need to do that.

### Reproduction

```
❯ git commit -a --fix 658e27ded92d7ae520770d9f00cbbd6c0ed69e3c
? Choose a gitmoji: (Use arrow keys or type to search)
❯ 🎨  - Improve structure / format of the code. 
  ⚡️  - Improve performance. 
  🔥  - Remove code or files. 
  🐛  - Fix a bug. 
  🚑️  - Critical hotfix. 
  ✨  - Introduce new features. 
  📝  - Add or update documentation. 
(Move up and down to reveal more choices)
[drop-run-in-thread 38ac8cc3] fixup! 🧵 (zb,internal): Replace run_in_thread with Task::spawn_blocking
 1 file changed, 5 insertions(+), 2 deletions(-)
```

### System Info

```Shell
System:
    OS: Linux 6.2 Fedora Linux 38 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 46.02 GB / 62.21 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/bin/node
    npm: 9.5.0 - /usr/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment] 2023-05-30 13:25
Hey!

Indeed, this is a duplicate of #1037

**Closed by carloscuesta** 2023-05-30 13:25 UTC
Labels: feature
