### ISSUE TITLE
[Feature request] Project (local) config with gitmojis specific to that particular project

### ISSUE THREAD

**Issue by dekadentno** [carloscuesta/gitmoji-cli#468] opened 2020-10-05 11:45 UTC
Hello @carloscuesta!

The emoji list is really big. It would be nice to have a way to provide a custom emoji list for every project. Currently, the emoji list is taken from [here](https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json)

**OS**: Ubuntu 20.04.1 LTS
**gitmoji -v**: 3.2.12
**Node version**: 12.18.1

**Comment by carloscuesta** [comment] 2020-12-19 09:19
Closing this as a duplicate of https://github.com/carloscuesta/gitmoji-cli/issues/59

Thanks for opening the issue @dekadentno

**Closed by carloscuesta** 2020-12-19 09:19 UTC
Labels: feature
