### ISSUE TITLE
[Feature Request] Escape double quotes in commit title

### ISSUE THREAD

**Issue by m-roberts** [carloscuesta/gitmoji-cli#148] opened 2018-11-28 08:53 UTC
Hello @carloscuesta!

If a commit message has double quotes (`"`) in it, it will fail. It would be great to escape these automatically, so that the escape characters do not contribute towards the character count.

**Comment by carloscuesta** [comment] 2019-11-10 16:37
Just checking this out, I'm a little bit confused, what do you mean by 

> If a commit message has double quotes (") in it, it will fail. 

The cli itself does not fails when including double quotes on the commit message or title

**Comment by carloscuesta** [comment] 2020-02-01 11:13
Closing this since I was not able to reproduce it 😕 

<img width="1440" alt="Screenshot 2020-02-01 at 12 13 31" src="https://user-images.githubusercontent.com/7629661/73591220-493e1f00-44ec-11ea-90eb-047bf57e07db.png">

**Closed by carloscuesta** 2020-02-01 11:13 UTC
Labels: bug
