### ISSUE TITLE
Windows display problem in hook mode

### ISSUE THREAD

**Issue by OpenWaygate** [carloscuesta/gitmoji-cli#831] opened 2022-05-07 17:31 UTC
Hello @carloscuesta!

Issue:

The updated status is append instead of replace in place after my operations(Use arrow keys or type to search).

This happens in cmd, powershell and git-bash, in windows terminal or classic console host. But not in client mode.

```
test on master  +1
➜ git commit
? Choose a gitmoji: (Use arrow keys or type to search)
> 🎨  - Improve structure / format of the code.
  ⚡️  - Improve performance.
  🔥  - Remove code or files.
  🐛  - Fix a bug.
  🚑️  - Critical hotfix.
  ✨  - Introduce new features.
  📝  - Add or update documentation.
(Move up and down to reveal more choices)? Choose a gitmoji: b
> 🎨  - Improve structure / format of the code.
  ⚡️  - Improve performance.
  🔥  - Remove code or files.
  🐛  - Fix a bug.
  🚑️  - Critical hotfix.
  ✨  - Introduce new features.
  📝  - Add or update documentation.
(Move up and down to reveal more choices)? Choose a gitmoji: b
  Searching...? Choose a gitmoji: b
> 🐛  - Fix a bug.
  💥  - Introduce breaking changes.
  👥  - Add or update contributor(s).
  🎉  - Begin a project.
  🔖  - Release / Version tags.
  🍱  - Add or update assets.
  💡  - Add or update comments in source code.
(Move up and down to reveal more choices)? Choose a gitmoji: be
> 🐛  - Fix a bug.
  💥  - Introduce breaking changes.
  👥  - Add or update contributor(s).
  🎉  - Begin a project.
  🔖  - Release / Version tags.
  🍱  - Add or update assets.
  💡  - Add or update comments in source code.
(Move up and down to reveal more choices)? Choose a gitmoji: be
  Searching...? Choose a gitmoji: be
> 🎉  - Begin a project.
  🍱  - Add or update assets.
  🍻  - Write code drunkenly.
  🏷️  - Add or update types.
  🌐  - Internationalization and localization.
  🧪  - Add a failing test.
  ♻️  - Refactor code.
(Move up and down to reveal more choices)
```

**OS**: Windows 11 22H2
**gitmoji -v**: 5.0.0
**Node version**: 16.14.0

**Error Message**:

**Comment by carloscuesta** [comment] 2022-05-08 18:06
Hey!

This is a duplicate of https://github.com/carloscuesta/gitmoji-cli/issues/93

**Closed by carloscuesta** 2022-05-08 18:06 UTC
