### ISSUE TITLE
ERROR: Network connection not found - ECONNABORTED (proxy issue?)

### ISSUE THREAD

**Issue by arnauldvm** [carloscuesta/gitmoji-cli#40] opened 2017-04-13 15:04 UTC
Hello @carloscuesta!

Can't get gitmoji to work (at all) in our infrastructure.

I suspect an issue with my proxy (I'm using CNTLM running on localhost:8080, see below).
As far as i could see, the requests from gitmoji-cli do not hit my proxy.
(But I don't see what could be wrong with my config.)

Issue:
```cmd
> npm install -g gitmoji-cli
(...)
> echo %http_proxy% - %https_proxy%
http://localhost:8080 - http://localhost:8080
> npm config get http-proxy & npm config get https-proxy
http://localhost:8080
http://localhost:8080/
> gitmoji -c
ERROR: Network connection not found - ECONNABORTED
```
then I have to hit `Ctrl+C`, and:
```javascript
TypeError: Cannot read property 'filter' of undefined
    at Object.questions.source.Promise.resolve.gitmojis.filter [as source] (D:\var\npm\node_modules\gitmoji-cli\src\gitmoji.js:146:7)
    at Prompt.search (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js:172:30)
    at Prompt._run (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js:70:8)
    at Prompt.<anonymous> (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\node_modules\inquirer\lib\prompts\base.js:56:10)
    at Prompt.run (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\node_modules\inquirer\lib\prompts\base.js:55:10)
    at null.<anonymous> (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer\lib\ui\prompt.js:78:56)
    at tryCatcher (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:63:31)
    at Defer.subscribeCore (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:2536:37)
    at Defer.tryCatcher (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:63:31)
    at setDisposable (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:2082:46)
readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'filter' of undefined
    at Object.questions.source.Promise.resolve.gitmojis.filter [as source] (D:\var\npm\node_modules\gitmoji-cli\src\gitmoji.js:146:7)
    at Prompt.search (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js:172:30)
    at Prompt.onKeypress (D:\var\npm\node_modules\gitmoji-cli\node_modules\inquirer-autocomplete-prompt\index.js:228:12)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:1762:31)
    at AnonymousObserver.tryCatcher (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:1762:31)
    at TakeWhileObserver.next (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:5701:17)
    at TakeWhileObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (D:\var\npm\node_modules\gitmoji-cli\node_modules\rx\dist\rx.js:1762:31)
```

**OS**: Windows 7 Enterprise SP1
**gitmoji-cli -v**: 1.5.1
**Node version**: 4.4.7
**npm version**: 3.10.3

**Error Message**: (see above trace)

**Comment by carloscuesta** [comment] 2017-04-13 17:37
Hey @arnauldvm 

What's failing is Axios making the request to get the emojis.json from the main repository. The error shown `ERROR: Network connection not found - ECONNABORTED` is thrown directly from Axios. Closing this issue since it's not a bug from the client.

**Closed by carloscuesta** 2017-04-13 17:37 UTC
